// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Ru83iFAcTMLfr-e2uoc69_6xm32EGzQ',
    appId: '1:859630146756:web:e896fd52aab282a2c26591',
    messagingSenderId: '859630146756',
    projectId: 'project1-98dae',
    authDomain: 'project1-98dae.firebaseapp.com',
    storageBucket: 'project1-98dae.firebasestorage.app',
    measurementId: 'G-LPYXSW1K21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq_8eyST5WLUBlpg0EKlixgST5xa2ktL8',
    appId: '1:859630146756:android:950e3cafd6d6b207c26591',
    messagingSenderId: '859630146756',
    projectId: 'project1-98dae',
    storageBucket: 'project1-98dae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATkSAPXW0DyqnXD5nsFMnp2MKztYazEBw',
    appId: '1:859630146756:ios:e518c6e5785d2537c26591',
    messagingSenderId: '859630146756',
    projectId: 'project1-98dae',
    storageBucket: 'project1-98dae.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATkSAPXW0DyqnXD5nsFMnp2MKztYazEBw',
    appId: '1:859630146756:ios:e518c6e5785d2537c26591',
    messagingSenderId: '859630146756',
    projectId: 'project1-98dae',
    storageBucket: 'project1-98dae.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Ru83iFAcTMLfr-e2uoc69_6xm32EGzQ',
    appId: '1:859630146756:web:2fa474fbc6f7416cc26591',
    messagingSenderId: '859630146756',
    projectId: 'project1-98dae',
    authDomain: 'project1-98dae.firebaseapp.com',
    storageBucket: 'project1-98dae.firebasestorage.app',
    measurementId: 'G-RCH11MMF87',
  );
}
